# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af7eff3cdea5cabee87d70c2302edce78f3e09a71a721dd7598a9a151e088cc5548e208e83edb27438fdc8cfe2cb3a895d467e46ad373d4f33ab059fb1bace85

test:
  secret_key_base: 21127d44764d45eb074adc3a2ad7df54ed99fb31b83f4582857227e0190df0c93b0e0cf43a111e3c78d753ff69551d770482d7a71d8e9ce35478db435dbd5247

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
